# Generated by Django 4.2.4 on 2023-08-29 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintainerComment",
            fields=[],
            options={
                "verbose_name": "댓글 (관리자용)",
                "verbose_name_plural": "댓글들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("post.comment",),
        ),
    ]
