# Generated by Django 4.2.4 on 2023-08-29 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintainerModal",
            fields=[],
            options={
                "verbose_name": "모달창 (관리자용)",
                "verbose_name_plural": "모달창들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notice.modal",),
        ),
        migrations.CreateModel(
            name="MaintainerNotification",
            fields=[],
            options={
                "verbose_name": "공지글 (관리자용)",
                "verbose_name_plural": "공지글들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notice.notification",),
        ),
    ]
