# Generated by Django 4.2.4 on 2023-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(default="")),
                ("contact", models.EmailField(blank=True, max_length=254, null=True)),
                ("memo", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaintainerSuggestion",
            fields=[],
            options={
                "verbose_name": "건의사항 (관리자용)",
                "verbose_name_plural": "건의사항들 (관리자용)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("suggestion.suggestion",),
        ),
    ]
