# backend/.github/workflows/ci-cd.yml
name: Django CI/CD

on:
  push:
    branches: [ product ]

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create .env file
      run: |
        touch .env
        echo SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
        echo DEBUG=${{ secrets.DJANGO_DEBUG }} >> .env
        echo API_URL=${{ secrets.DJANGO_API_URL }} >> .env
        echo WEB_URL=${{ secrets.DJANGO_WEB_URL }} >> .env
        echo FE_WEB_URL=${{ secrets.DJANGO_FE_WEB_URL }} >> .env
        echo DISCORD_WEBHOOK_URL_NEMO=${{ secrets.DISCORD_WEBHOOK_URL_NEMO }} >> .env
        echo DISCORD_WEBHOOK_URL_COMMON=${{ secrets.DISCORD_WEBHOOK_URL_COMMON }} >> .env
        echo DISCORD_WEBHOOK_URL_COMMENT=${{ secrets.DISCORD_WEBHOOK_URL_COMMENT }} >> .env
        echo DISCORD_WEBHOOK_URL_SUGGESTION=${{ secrets.DISCORD_WEBHOOK_URL_SUGGESTION }} >> .env
        echo DISCORD_WEBHOOK_URL_UPLOAD=${{ secrets.DISCORD_WEBHOOK_URL_UPLOAD }} >> .env
        echo DISCORD_WEBHOOK_URL_TEST=${{ secrets.DISCORD_WEBHOOK_URL_TEST }} >> .env
        echo DATABASE_NAME=${{ secrets.DJANGO_DATABASE_NAME }} >> .env
        echo DATABASE_USER=${{ secrets.DJANGO_DATABASE_USER }} >> .env
        echo DATABASE_PASSWORD=${{ secrets.DJANGO_DATABASE_PASSWORD }} >> .env
        echo DATABASE_HOST=${{ secrets.DJANGO_DATABASE_HOST }} >> .env
        echo DATABASE_PORT=${{ secrets.DJANGO_DATABASE_PORT }} >> .env

        cat .env

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t sangjune2000/bamboov2-back

    - name: Push to Docker Hub
      run: docker push sangjune2000/bamboov2-back

  CD:
    needs: [ CI ]
    runs-on: ubuntu-latest

    steps:
    - name: Login to NCP Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
        username: ${{ secrets.NCP_ACCESS_KEY }}
        password: ${{ secrets.NCP_SECRET_KEY }}

    - name: Deploy with docker compose
      run: |
        docker-compose down
        docker-compose pull
        docker-compose up -d